<br /><br />
<div id="view-content">
	<div id="view-content">
	<table class="table">
	<tr>
		<th>link</th>
		<th>Delete</th>
	</tr>
	
		<?php foreach ($this->links as $value) {
		# code...
		?>
			<tr>
				<td><?php echo $value['url']?></td>
				<td><a href="#">Delete</a></td>
				<td></td>
			</tr>
		<?php
	} ?>	
	</table>
	<a href="<?php echo $this->baseUrl();?>/rssfeed/add" class="btn btn-primary">+ ADD Feed Link</a>
</div>
</div>